definitions:
  dto.UserRequestDTO:
    properties:
      age:
        type: integer
      gender:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserRequestDTO'
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - user
swagger: "2.0"
