definitions:
  dto.UserResponseDTO:
    properties:
      age:
        type: integer
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.UserResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Create a new user
      tags:
      - user
  /users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Find user by ID
      tags:
      - user
    put:
      consumes:
      - application/json
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponseDTO'
      security:
      - ApiKeyAuth: []
      summary: Update user
      tags:
      - user
swagger: "2.0"
